### ISSUE TITLE
react-datetime.d.ts cannot find namespace __react

### ISSUE THREAD

**Issue by vissermc** [YouCanBookMe/react-datetime#215] opened 2016-12-15 08:33 UTC
Typescript compilation error on:

import React = __React;

 error TS2503: Cannot find namespace '__React'.

**Comment by PeterKottas** [comment] 2016-12-15 10:33
Duplicate of #181 It seems the guys here already have a solution and I am desperately waiting to get a new release for it.  Funny thing is I can't actually fix it myself. Adding exclude "node_modules/react-datetime/react-datetime.d.ts" to tsconfig.json doesn't work as it's strictly mentioned in the npm package.json. I haven't yet found a way to exclude it that way and provide my own instead.

**Comment by vissermc** [comment] 2016-12-15 14:55
I just removed that line and made my own fork and updated my package.json to

"react-datetime": "https://github.com/vissermc/react-datetime.git#512bf6f7c3f664b8268de9b3d68e4671feda903c",

**Comment by ncphillips** [comment] 2016-12-16 14:37
I have another alternative. I copied the React typings, renamed the variables to `__React`, and added them to our custom typings. It doesn't conflict with the actual `react` typings, but it fixes this issue.

Example:

```

export = __React;
export as namespace __React;

declare namespace __React {

  //
  // React Elements
  // ----------------------------------------------------------------------

  type ReactType = string | ComponentClass<any> | StatelessComponent<any>;

  type Key = string | number;
  type Ref<T> = string | ((instance: T) => any);
  type ComponentState = {} | void;

// and so on....
```

**Comment by simeg** [comment] 2016-12-20 20:11
Hi @vissermc, @PeterKottas and @ncphillips. 

The PR handling this issue has been merged and version 2.8.0 just got released. Hopefully it will resolve your problems, thanks.

**Closed by simeg** 2016-12-20 20:11 UTC

**Comment by PeterKottas** [comment] 2016-12-23 10:13
Perfect @simeg will update now. Thanks!

**Comment by stonecold123** [comment] 2016-12-29 12:25
I don't see any change in the d.ts file in 2.8.1.

**Comment by simeg** [comment] 2016-12-29 19:34
@PeterKottas did you manage to get this working? I don't have a TS environment set up so I'm not sure how to troubleshoot this..

@stonecold123 the `index.d.ts` file is located in the `typings` folder, are you looking there?

**Comment by PeterKottas** [comment] 2016-12-31 08:09
Hi @simeg this still appears to be a problem in the recent release. Seems like you might have forgotten to merge. Typings are still wrong. Take a look at https://github.com/vissermc/react-datetime.git#512bf6f7c3f664b8268de9b3d68e4671feda903c which is working for me. You just need to comment out the line with react basically.

**Comment by simeg** [comment] 2017-01-06 20:20
@PeterKottas Could you please see if this bug still exists, now that you have the updated version? Thanks a lot.
