### ISSUE TITLE
Current Year Not Selectable in Year View 

### ISSUE THREAD

**Issue by layneanderson** [YouCanBookMe/react-datetime#243] opened 2017-01-10 16:44 UTC
With `validDate` set to not allow future dates if the user backs out to year view, 2017 is disabled and not selectable.

_Additional Info_
A user workaround is available by choosing 2016 and then using the arrow (>) to increment year to 2017.

**Comment by simeg** [comment] 2017-01-10 20:10
Thanks for notifying. It's probably a duplicate of this issue: https://github.com/YouCanBookMe/react-datetime/issues/192

**Closed by simeg** 2017-01-10 20:10 UTC
