### ISSUE TITLE
onBlur event triggers only when choosing values from the calendar

### ISSUE THREAD

**Issue by ivag** [YouCanBookMe/react-datetime#174] opened 2016-10-26 13:54 UTC
Hello,

I'm using react-datetime@2.6.0 and i have question about onBlur event:
1) I select a date from the calendar, e.g. 2016-10-10 
2)  Then i change the value to 2016-10-1 which is invalid date and i'm using onBlur event because i want to revert it to the old value: 2016-10-10.
But onBlur() triggers only when i choose dates from the calendar, not when i leave the focus of the input field. Is there any possibility to change this?

Thanks a lot!

**Comment by simeg** [comment] 2016-11-08 21:43
Hi @ivag. 

When you say "when i leave the focus of the input field", do you mean that you use the TAB key to move away from the input field? Or how do you switch focus?

**Comment by ivag** [comment] 2016-11-08 21:52
I meant 'leave the focus' by clicking outside the input file(date field) or
selecting another field. I'm not using TAB.

On Nov 8, 2016 10:43 PM, "Simon Egersand" <notifications@github.com> wrote:
>
> Hi @ivag.
>
> When you say "when i leave the focus of the input field", do you mean
that you use the TAB key to move away from the input field? Or how do you
switch focus?

**Comment by simeg** [comment] 2016-11-08 21:56
I'll look into this, it sounds weird. Thanks.

**Comment by ivag** [comment] 2016-11-08 22:07
The thing is that, i want to implement a validation in case the user enters invalid date manually (typing the date). Tell me if you need more details in order to reproduce it. Thanks.

**Comment by simeg** [comment] 2016-11-08 22:34
I'm unable to reproduce this using 2.6.0. As you can see here on [line 334](https://github.com/YouCanBookMe/react-datetime/blob/master/DateTime.js#L334) the `onBlur` method is called on `handleClickOutside`. It would help if you could reproduce your exact environment in codepen ([here's a project which you can fork](http://codepen.io/simeg/pen/mEmQmP)).

**Comment by alainesse** [comment] 2016-11-23 19:45
If the open prop is true, the onBlur is not called on the inputs onBlur

**Comment by simeg** [comment] 2016-11-23 19:46
@alainesse are you using the latest version?

**Comment by alainesse** [comment] 2016-11-23 19:46
@simeg 2.7.5

**Comment by alainesse** [comment] 2016-11-23 19:49
http://codepen.io/anon/pen/Mbmdde

**Comment by simeg** [comment] 2016-11-23 19:52
Yes, I can see it. I'll look into it. I'm guessing this is the same bug @ivag is referring to.

**Comment by simeg** [comment] 2016-11-23 20:21
@alainesse in what way do you trigger the `onBlur` of the input element when the calendar is open? By focusing it and then pressing tab?

**Comment by alainesse** [comment] 2016-11-23 20:35
@simeg clicking outside the input box.

**Comment by arqex** [comment] 2016-11-24 09:26
I think some other devs already have the same confusion. react-datetime's `onBlur` event is not the input event. It was a bad decission to call it that way, a better name would have been `onClose` because only happens when the calendar closes.

If anybody needs the real `blur` event from the input, please use `inputProps`. You can bind any event handler that you need from the input element:

```
<datetime inputProps={{onBlur: ev => console.log('Do whatever', ev) }} />
```

**Comment by simeg** [comment] 2016-11-24 09:37
@arqex that makes sense, then we should update the README because now it says
>**onBlur**: Callback trigger for when the user **clicks outside of the input**, simulating a regular onBlur.

This is a good candidate for v3, to change to `onClose` and maybe introduce `onBlur` for the input.

Closing this now. @ivag @alainesse use the solution posted above.

**Closed by simeg** 2016-11-24 09:37 UTC

**Comment by solomon23** [comment] 2016-12-02 22:43
Running into a similar issue that @arqex's solution doesn't fix.  I want to show a link.  When the link is clicked I want to show the input with the calendar open.  So i set the prop `open={true}` and add the calendar to the dom.  But when clicking outside the calendar I want to grab it's value, close it and hide it.  with `open={true}` the blur event never fires ( which now makes sense ) but I'd like an event to know when clicking outside the calendar and input that would normally cause a close
