### ISSUE TITLE
"open" prop issue

### ISSUE THREAD

**Issue by Youpinadi** [YouCanBookMe/react-datetime#44] opened 2015-12-09 15:07 UTC
Hi,

I have a component that wraps a DateTime (there is a small button with a calendar icon at the end).

Here is the code 

``` javascript
import React, {Component, PropTypes} from 'react'
import FormInput from 'components/form/form-input/form-input.jsx'
import ReactDatetime from 'react-datetime'

export default class Datetime extends Component {
  state = {
    open: false
  }
  toggleOpen() {
    this.setState({open: !this.state.open})
  }

  render() {
    let {error,hint,className,...other } = this.props

    return (
      <FormInput className={`form_datetime form_input--merged ${this.props.className}`} error={this.props.error} hint={this.props.hint}>
        <ReactDatetime {...other} open={this.state.open}/>
        <button className="btn icon-end" onClick={::this.toggleOpen}><i className="icon icon-calendar"/></button>
      </FormInput>
    )
  }
}
```

Changing state.open doesn't do anything
I already tried a patch in `componentWillReceiveProps`:

``` javascript
if( nextProps.value != this.props.value || nextProps.open != this.props.open) {
    update = this.getStateFromProps( nextProps );
}
```

But when i do this, the calendar won't close on blur.

Basically i just want to be able to control the opening of a calendar, but the open prop doesn't do it.

Thanks in advance,

Nadir

**Comment by halkeye** [comment] 2015-12-13 05:28
what about 
```js
DateTime.prototype.componentWillReceiveProps = function (nextProps) {
  if (this.props.open !== nextProps.open) {
    this.setState({ open: nextProps.open });
  }
};
```

**Comment by C3PablO** [comment] 2016-06-02 14:20
I had the same problem and I solved it using the answer at issue #57 using `this.refs.picker.closeCalendar()`. That works but the `open` prop it's another matter. I think that is working just for the initial state

**Comment by schickling** [comment] 2016-07-23 14:12
This seems like a bug. Applying @halkeye's fix works for me.

Could you please merge this in @arqex @simeg?

**Comment by TheSharpieOne** [comment] 2016-08-12 20:48
A larger problem which affects all of the props is that they currently cannot be changed unless the `value` prop is changed.

[this](https://github.com/YouCanBookMe/react-datetime/blob/master/DateTime.js#L150-L152) only sets the update props when value has changed.

**Comment by goooseman** [comment] 2016-08-22 08:21
Maybe it is a hack, but I've coped with this issue, just passing `hidden` className (which sets display: none) to `DateTime` like this:
```
<DateTime
        input={false}
        open
        className={props.dateBoxOpened ? '' : 'hidden'} />
```

**Comment by simeg** [comment] 2016-09-13 00:10
I think we should consider adding more props to be checked inside the `componentWillReceiveProps`, but I don't know what props and why/why not. The point that @TheSharpieOne is making about that `value` prop is triggering all other props to update is also worth thinking about. Maybe you want to change the `locale` without having to change the value? I'm sure there's more props you want to do check separately. I think @arqex might have some knowledge and opinions about this.

Reading this issue I can also spot another question. The `open` prop is a bit undefined to me. It's not a pure state prop in that sense that it also affects if you are able to close the datepicker. And is that behaviour even wanted? As I said - not very clear what it does and what it's suppose to do. Do you know @arqex?

Labeling as `solution` during in the meantime as it contains a workaround.

**Comment by TheSharpieOne** [comment] 2016-09-13 04:44
The real question is why limit this? Are you checking for specific props to change for performance reasons? Usually you can just check that the props object is the same and if it isn't, then update the state. Whether open prop changed or the locale prop changed or any other prop changed shouldn't matter, they should all trigger a render. Performance-wise, if the developer to constantly changing props and causing rerenders, it is not this project's fault. React would end up diff'ing the new and the old render and determining if a change needs to go to the DOM. Since there is only a [limited set of props](https://github.com/YouCanBookMe/react-datetime#api) that do affect the render, you can add a `shouldComponentUpdate` to maybe determine that [ANY of the props](https://github.com/YouCanBookMe/react-datetime#api) that would affect the render have changed.

**Comment by arqex** [comment] 2016-09-13 14:35
The problem is not re-rendering after props updating. It actually happens, the component gets rerendered. As @simeg said, there are some props that are not pure props, but initial state ones.

Everybody likes the component to open and close on focus or clicking outside out of the calendar, so the fact that it's open is not handled by the prop directly, but by the internal state of the component.

There are 2 options here, or either we make the component controlled:

https://facebook.github.io/react/docs/forms.html#controlled-components

so if you want to open or close the component you can set `open` to `true` or `false`, but you also will need to listen to the `focus`, `click` or `clickOutside` events yourself, in order to set the prop properly. The component wouln't do that work for you any longer.

Or the second solution should be making public the imperative API to open/close calendar whenever it's needed. As @C3PablO said, it's possible to create a reference to the picker and do 
```
this.refs.picker.openCalendar();
this.refs.picker.closeCalendar();
```
Then the `open` feature should be renamed to something like `initiallyOpen`. This is against what every functional programmer would advice, but it would keep the autoclose/open behaviour of react-datetime.

This happens to some other props of this component.

It's a matter of ballance:
* Make your component completelly functional and you will make your component users code all the functionality for it (when to open the calendar, when to switch the view, what month to show).
* Give an internal state to the component to pack some functionality in it and you will taking some control from the users (the calendar will open/close automatically or switch to the day view when you click on a month ).

From my point of view, I love components that you can throw to your project and it works out of the box, and I don't need to set them up with a bunch of code. So I don't care to use a well designed imperative API if it let me code much less.

There are some other props like the `locale` one that it's not working on change and the component is never updating it, so it should be pure. We would need to go through all props and see which one are pure and which aren't.

**Comment by TheSharpieOne** [comment] 2016-09-13 15:39
The other option, which is less invasive than using refs imo is a callback. Let the user know that the calendar was shown or hidden, `onToggle(isOpen)`, they can control the component but not have as much manual process
This is more like the controlled components you mention, but without having to manually listen for all of those events.
```
<DateTime onToggle={isOpen => this.setState({isOpen: isOpen})} open={this.props.isOpen}/>
```
(for the sake of 1 line example, ignore the `jsx-bind`)

It's very similar to an input's `onChange` setting it's `value` for controlled inputs.

You can still keep the default internal functionality if open is not passed / is undefined.

**Comment by simeg** [comment] 2018-02-11 20:52
This has been fixed in a recent version, the `open` prop should work as you would think it worked.

**Closed by simeg** 2018-02-11 20:52 UTC
Labels: documentation
