### ISSUE TITLE
onFocus is missing `event` as argument

### ISSUE THREAD

**Issue by alvinsj** [YouCanBookMe/react-datetime#422] opened 2017-09-13 05:50 UTC
### I'm Submitting a ...

```
[X] Bug report
[X] Feature request
[ ] Support request
```

### Steps to Reproduce

1. `<DateTime onFocus={e => console.log(e.target)} />`
2. click on the input to focus
### Expected Results

console output: `<input />`
### Actual Results

console error: `Cannot read property 'target' of undefined`
### Minimal Reproduction of the Problem

https://codepen.io/anon/pen/GMRdba

**Comment by simeg** [comment] 2017-11-02 21:06
Confirmed, it doesn't output anything. I have a fix on-going but I can't get it to build because of some dependency issues: https://github.com/YouCanBookMe/react-datetime/pull/455

Closing this for now though, follow the PR.

**Closed by simeg** 2017-11-02 21:06 UTC
