### ISSUE TITLE
componentWillReceiveProps Warnings cluttering console - please either rename it to UNSAFE_componentWillReceiveProps or swap them to componentDidUpdate

### ISSUE THREAD

**Issue by afcjunior** [YouCanBookMe/react-datetime#673] opened 2019-12-13 15:17 UTC
Version used: 2.16.3

### I'm Submitting a ...

```
[ ] Bug report
[ ] Feature request
[X] Support request
```

### Steps to Reproduce

1. import DateTime from 'react-datetime';2. Use the component (I passed it Onchange, defaultValue and inputProps, althought I don't believe this matters).

### Expected Results

It should work without warnings.

### Actual Results

It works but displays a warning on my console:

Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

**Comment by felipecarrillo100** [comment] 2019-12-14 00:44
Seems a dupplicate of #671

**Comment by jaagupku** [comment] 2019-12-16 09:13
Duplicate of #649

**Comment by arqex** [comment] 2020-01-19 19:06
Yes, duplicated of https://github.com/YouCanBookMe/react-datetime/issues/649

It's going to be fixed in v3

**Closed by arqex** 2020-01-19 19:06 UTC
