### ISSUE TITLE
Set state from updated props

### ISSUE THREAD

**Issue by Krzyku** [YouCanBookMe/react-datetime#343] opened 2017-06-02 09:30 UTC
### I'm Submitting a ...
```
[x] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce
Wrap DateTime component in Your custom component. Now try to toggle DateTime `open` prop.

### Expected Results
Show and hide datepicker

### Actual Results
Nothing happen

### Minimal Reproduction of the Problem
https://codepen.io/krzyk/pen/JJPxyY

### Other Information (e.g. stacktraces, related issues, suggestions how to fix)
In `DateTime.js` change line inside `componentWillReceiveProps` method from `updatedState.open = this.state.open;` to `updatedState.open = nextProps.open;`

**Comment by LuciRebecca** [comment] 2017-06-23 13:44
I ran into this today as well and the above resolution from @Krzyku worked for me

**Comment by MatthiasDebaere** [comment] 2017-06-27 14:23
We also ran into this today. Can we get this merged, please?

**Comment by fernandops26** [comment] 2017-07-09 00:55
since that version?

**Comment by NullVoxPopuli** [comment] 2017-08-16 13:47
this is the technique I use for opening the picker:
```js
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import ReactDateTime from 'react-datetime';
import { InputGroup } from 'react-bootstrap';

const InputAddon = InputGroup.Addon;

export default class DatePicker extends Component {
  constructor(props) {
    super(props);

    this.pickerRef = null;
  }

  render() {
    const open = () => this.pickerRef && this.pickerRef.openCalendar();

    return (
      <InputGroup>
        <ReactDateTime
          { ...this.props }
          ref={ref => { this.pickerRef = ref; }}
        />

        <InputAddon onClick={open}>
          <i className='fa fa-calendar' aria-hidden='true'></i>
        </InputAddon>
      </InputGroup>
    );
  }
}

```

**Comment by SachaG** [comment] 2017-11-14 02:35
Still doesn't seem to be working for me with the latest version.

**Comment by eyanez1230** [comment] 2017-12-01 18:05
Does not work for me either with the latest version

**Comment by simeg** [comment] 2017-12-01 23:09
@Krzyku @LuciRebecca @MatthiasDebaere @fernandops26 @NullVoxPopuli @SachaG @eyanez1230 

Please try version 2.11.1 and let me know if it worked for you. Thanks.

**Comment by eyanez1230** [comment] 2017-12-02 00:29
@simeg Confirming that it is now fixed! Thank you very much.

**Comment by SachaG** [comment] 2017-12-06 02:38
Thanks for fixing the issue! But this lead me to find a related issue: when you make the calendar open by setting `open` to `true`, you can't click out of it to close it anymore. And the `onBlur` event callback doesn't trigger either. Is this the intended behavior?

By the way I've also tried using `this.calendar.openCalendar()` because it fits my needs better (I just want to open the calendar once, not keep it open permanently) but that didn't work either.

**Comment by eyanez1230** [comment] 2017-12-06 17:24
@SachaG +1 also facing this same issue.

**Comment by simeg** [comment] 2018-02-01 19:00
@SachaG Could you make a separate issue with a detailed explanation of your problem? It would make things easier for us. Thanks.

**Closed by simeg** 2018-02-01 19:00 UTC
Labels: action needed
